### ISSUE TITLE
R U ready to record audio?

### ISSUE THREAD

**Issue by linjiansheng** [yrom/ScreenRecorder#1]
RT!

**Comment by danishrazaa** [comment]
How to record voice along with video in this Demo?

**Comment by DonLiangGit** [comment]
In this demo, yrom only shows the flow using lollipop mediaprojection api. There are not any record voice in his example. I think you need MediaRecorder if you wanna record audio from mic, or for internal audio probably you need to grab more info regarding to SCR recorder.

**Comment by tomasvalek** [comment]
I tried via MediaRecorder, but it is very slow.
http://stackoverflow.com/questions/35825963/android-media-projection-record-screen-video-low-framerate
Do you have record media projection with audio from microphone?

**Comment by JeongChanYoung** [comment]
In my repository, there is a voice recorder along video. I used this project.
