### ISSUE TITLE
No way to stop ongoing recording

### ISSUE THREAD

**Issue by umair1209** [yrom/ScreenRecorder#16]
#### Expected behavior
After starting the recording we should be able to stop it somewhere. 

#### Actual behavior
I recently installed screen recorder app and started a recording and the app did start and while I was done recording, I wanted to finish it so I started looking for stop option but to my surprise I didn't find any. 
How are we supposed to record something if we can't stop the recording. 

#### How to reproduce
- Open screenrecorder and start recording 
- You won't be able to stop recording. 
(Clear the data or uninstall the app if you are not able to reproduce the bug). 

* Browser: Screen Recorder v2.4
* Operating system: Android 6.0.1

#### Recording Of The Bug

https://youtu.be/OkXLh2rdShc    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@syedumair/no-way-to-stop-ongoing-recording">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by yrom** [comment]
Hi, you may have overlooked recording notification.
![device-2018-03-02-105958](https://user-images.githubusercontent.com/2888674/36881511-6f18fcce-1e09-11e8-9307-369c0213801b.png)
