### ISSUE TITLE
Screen Recording isn't saved anywhere on the device 

### ISSUE THREAD

**Issue by umair1209** [yrom/ScreenRecorder#17]
#### Expected behavior
When you record something on your screen using screen recording apps, you are able to watch those videos as they are saved on your device. 

#### Actual behavior
While the screen recorder shows that it is recording a video but in reality there is no way to watch that video. 
It is not saved anywhere on the device as there is no path for saving the video. 

#### How to reproduce
- Simply start recording on screen recorder and after the recording is finished you won't be able to locate the video. 

* Browser: screen recorder v2.4
* Operating system: Android 6.0.1

#### Recording Of The Bug

    Now I cannot record a gif or video to show the above bug so let me show a picture 

![Screenshot_2018-02-28-14-46-48-421_net.yrom.screenrecorder.demo.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1519814132/avrehmcwyo7pm5otitjd.png)

As can be seen from the above picture that there is no path to save your recorded videos. 

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@syedumair/screen-recording-isn-t-saved-anywhere-on-the-device">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by yrom** [comment]
Yeah, this is a very very simple app that just a demonstration of android screen-capture apis. You can edit the saving path by yourself.
Actually, it was located at `/sdcard/Movies` if successful recording
