### ISSUE TITLE
video can't be play

### ISSUE THREAD

**Issue by HemendraGangwar** [yrom/ScreenRecorder#2]
this demo create the video but when is play give the message this video can't be played in lolipop device please give a solution .

**Comment by hemkumar1100gmailcom** [comment]
now the video is play but screen  goes to black and video seek bar moving

**Comment by yrom** [comment]
Have you try to modify *ScreenRecorder* initialization parameters like video width, height and bitrate?
[MainActivity.java#L55-L59](https://github.com/yrom/ScreenRecorder/blob/master/app/src/main/java/net/yrom/screenrecorder/MainActivity.java#L55-L59)
